spring.application.name=backend

frontend.url =http://localhost:5173/
image.base.url=http://localhost:8080/images

spring.datasource.url=jdbc:postgresql://localhost:5432/Ecom-WebApp
spring.datasource.username=postgres
spring.datasource.password=8524
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false