spring.application.name=backend
frontend.url =${FRONTEND_URL}
image.base.url=${IMAGE_BASE_URL}
project.image =${PROJECT_IMAGE}
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
spring.ecom.app.jwtCookieName=${JWT_COOKIE_NAME}
spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=${SECURITY_PASSWORD}
stripe.secret.key=${STRIPE_SECRET_KEY}